apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatroom.fullname" . }}
  labels:
    {{- include "chatroom.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatroom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatroom.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: chatroom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: chat-config
              mountPath: /config/chat-config.json
              subPath: chat-config.json
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
        - name: chat-config
          configMap:
            name: {{ include "chatroom.fullname" . }}-config
