replicaCount: 1

image:
  repository: oresperansa/sigit-messanger
  tag: "0.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  NODE_ENV: production
  PORT: "3000"
  CONFIG_PATH: /config/chat-config.json
  TRUST_PROXY: "true"

chatConfig:
  names:
    - Falcon
    - Wolf
    - Tiger
    - Eagle
    - Shadow
    - Rocket
  ipOverrides:
    "192.168.1.10": "Admin"
    "82.166.20.50": "Yuval"
